import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

// Plugin to load HTML files as strings (timeline HTML is bundled inline for mobile compatibility)
const htmlPlugin = {
  name: "html-loader",
  setup(build) {
    build.onLoad({ filter: /\.html$/ }, async (args) => {
      // Bundle all HTML files inline, including timeline HTML
      // This is required for mobile compatibility where runtime file loading doesn't work
      const html = await fs.promises.readFile(args.path, "utf8");
      return {
        contents: `export default ${JSON.stringify(html)};`,
        loader: "js",
      };
    });
  },
};

// Plugin to extract and merge CSS into styles.css
const cssPlugin = {
  name: "css-merge",
  setup(build) {
    // Collect CSS from imports
    const cssContents = [];

    build.onLoad({ filter: /\.css$/ }, async (args) => {
      const css = await fs.promises.readFile(args.path, "utf8");
      cssContents.push(`/* From: ${path.basename(args.path)} */\n${css}`);
      return { contents: "", loader: "js" };
    });

    build.onEnd(async () => {
      if (cssContents.length > 0) {
        // Read existing styles.css
        let existingStyles = "";
        const stylesPath = "./styles.css";
        if (fs.existsSync(stylesPath)) {
          existingStyles = await fs.promises.readFile(stylesPath, "utf8");
        }

        // Check if dhtmlx styles already added
        if (!existingStyles.includes("/* From: dhtmlxgantt.css */")) {
          // Append imported CSS to styles.css
          const mergedCSS = existingStyles + "\n\n/* === BUNDLED CSS IMPORTS === */\n" + cssContents.join("\n\n");
          await fs.promises.writeFile(stylesPath, mergedCSS);
          console.log("Merged CSS imports into styles.css");
        }
      }
    });
  },
};

// Plugin to copy build files to example-vault
const copyToExampleVault = {
  name: "copy-to-example-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;

      const targetDir = "./example-vault/.obsidian/plugins/planner";
      const filesToCopy = ["main.js", "manifest.json", "styles.css"];

      // Ensure target directory exists
      if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
      }

      for (const file of filesToCopy) {
        if (fs.existsSync(file)) {
          fs.copyFileSync(file, path.join(targetDir, file));
          console.log(`Copied ${file} to ${targetDir}`);
        }
      }

      // Copy timeline HTML separately (loaded at runtime to reduce bundle size)
      const timelineHtmlSrc = "./assets/timeline-markwhen.html";
      const timelineHtmlDest = path.join(targetDir, "timeline.html");
      if (fs.existsSync(timelineHtmlSrc)) {
        fs.copyFileSync(timelineHtmlSrc, timelineHtmlDest);
        console.log(`Copied timeline.html to ${targetDir}`);
      }
    });
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [htmlPlugin, cssPlugin, copyToExampleVault],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
